version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    ports:
      - "15672:15672" # GUI
      - "5672:5672"

  mysql:
    image: mysql:8.0
    container_name: pppd
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: pppd
      MYSQL_USER: user_pppd
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mysql-data: # 为MySQL定义一个命名卷