spring:
  profiles:
    active: dev
  application:
    name: ProgrammingPracticePlatform
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pppd?serverTimezone=UTC
    username: root
    password: 123456
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /SandboxService
    username: SandboxService
    password: 123456
    listener:
      simple:
        prefetch: 1
  redis:
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl